version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ttl_rip_db
    environment:
      - POSTGRES_USER=ttlrip
      - POSTGRES_PASSWORD=ttlrip
      - POSTGRES_DB=ttlrip
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: ttl_rip_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
